### ISSUE TITLE
error: map is undefined

### ISSUE THREAD

**Issue by Skrol29** [jorix/OL-DynamicMeasure#1]
Hi Jorix,

Thanks for this nice control enhancement.

I've found a bug in your code of file "DynamicMeasure.js" :
line 260, replace :

``` javascript
this.map.removeLayer(layer);
```

with :

``` javascript
if (layer.map) layer.map.removeLayer(layer);
```

The scope of this line is a temporary function not linked to the current objet. Thus variable "this" brings to the Window object, not the current DynamicMeasure object.

By the way, would it be better to code a layer.destroy() instead of a map.removeLayer() ?
Is this layer properly destroyed ?

**Comment by jorix** [comment]
@Skrol29 

Oops! How clumsy of me! 

See fix on ca9b21c9252b5e074ee26d5770e78b2ada6cd6b0

Thank you!

> By the way, would it be better to code a layer.destroy() instead of a map.removeLayer() ?

The creation of the layers is done in the constructor. But it is true that complicates the code of `deactivate` and `destroy` methods to gain nothing (approx. ;-|) I will study to move layer cration to activate method.

> Is this layer properly destroyed ? 

See `destroy` method.

**Comment by jorix** [comment]
> move layer creation to activate method.

Done in 1b9fba6803528fa18bd1aa04e525e1849f7d58e4

**Comment by jorix** [comment]
Closed: after commits no feedback, so it seems that the problem is fixed.
