### ISSUE TITLE
ModifyFeature

### ISSUE THREAD

**Issue by nigr0nyx** [jorix/OL-DynamicMeasure#10]
Thank you for your excellent tool!
It will be very helpful to use dynamic measurement for ModifyFeature control.

**Comment by jorix** [comment]
Thank you for your positive feedback. Currently I do not plan to work for OL2. 

I've done some work on ModifyFeature in another sense that you indicate, I do not know if you've looked at it: [extends-modifyfeature-control](https://github.com/jorix/OL-Ragbag#extends-modifyfeature-control)
