### ISSUE TITLE
Work with OpenLayers.Control.EditingToolbar ?

### ISSUE THREAD

**Issue by drupol** [jorix/OL-DynamicMeasure#2]
Hello Xavier,

I wanted to include this wonderful extension in a custom Drupal project using the EditingToolbar Control to create entry on a map.

When I enable them, only the EditingToolbar is working.

Do you think that there is a way to get them working both ?

Thanks my friend, have a nice week end.

**Comment by jorix** [comment]
Hi @Polzme 

Are you looking for something like this?

http://castelldefels.org/ca/mapes.asp?lang=en

Don't use EditingToolbar. I use a panel with CSS adjustments, I could make a control MeasureToolbar like of  castelldefels.org. 

What you think?

Including the icon?

**Comment by drupol** [comment]
First of all, wow, what a nice map ! Looks like you live in a nice and sunny place :-)

Second, no, in Drupal, we have a module called [Geofield](http://drupal.org/project/geofield), used to input data on a map.
It's using the EditingToolbar control (and copy the WKT into a hidden field, then save it in database... ).

It would be great to have those feature into the EditingToolbar though !

**Comment by jorix** [comment]
What you look for is measure and draw right? I could think of a control like `DrawMeasuringFeature` ...

NOTE: Since 2.11 I I don't like `EditingToolbar`: while you draw can not move the map. Some OL examples use a custom _EditingToolbar_ see http://openlayers.org/dev/examples/mobile-drawing.html which does not have this problem.

**Comment by drupol** [comment]
Yes it would be better.

I'm using GeoField, and Geofield is using [this JS](http://drupalcode.org/project/geofield.git/blob/refs/heads/7.x-2.x:/includes/behaviors/js/openlayers_behavior_geofield.js) to handle the drawing.

I'll try to see if I can modify it and enable your extension.

**Comment by jorix** [comment]
See branch _DrawMeasuring_ how could measure and draw on example [measure-and-draw.html](https://github.com/jorix/OL-DynamicMeasure/blob/DrawMeasuring/examples/measure-and-draw.html)

What you think?

**Comment by drupol** [comment]
Testing all of this right now, I've been quite busy these last days, sorry for that @jorix :(

**Comment by drupol** [comment]
Just amazing :-)
I'll see if I can use it in the Geofield module !

**Comment by jorix** [comment]
>  ...I've been quite busy these last days, sorry for that...

no problem, I think I understand how you work, hard on a theme, but you have different focuses that demand your attention and the day only has 24 hours ;-) 
(for me it is impossible to have the head in two place at one time)

**Comment by drupol** [comment]
Exact :+1:

**Comment by jorix** [comment]
DrawMeasuring branch is merged on gh-pages (used as a master)

**Comment by drupol** [comment]
I'm still on other stuff, but I should be back on this in 2 weeks :-)

**Comment by jorix** [comment]
Hi Pol,

When you have a moment I would like to know your opinion on example/modify-feature.html at the branch [modify-feature-tools](http://jorix.github.io/OL-Ragbag/examples/modify-feature.html) on OL-Ragbag (soon will publish in the gh-pages)

**Comment by jorix** [comment]
Done by [v1.1.0](https://github.com/jorix/OL-DynamicMeasure/tree/v1.1.0)
